In [36]:
import pandas as pd
import datetime as dt
import numpy as np

# net_degree

In [37]:
net_degree_3 = pd.read_pickle('net_degree_3.pkl')

In [38]:
net_degree_3.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,year_0,in_degree_0,out_degree_0,in_degree_1,out_degree_1,in_diff,out_diff,out_diff_ratio,in_diff_ratio,out_group
0,000360206,0.000848,0.000000,0.000000,0.000000,6.336145e-17,0.000000,2.000000,0.0,3.0,...,2003-06-30,0.0,3.0,0.0,3.0,0.0,0.0,0.000000,NaN,0
1,000361105,0.000000,0.000283,0.138689,0.000000,6.321229e-03,548.415620,0.000000,0.0,1.0,...,2003-06-30,1.0,0.0,0.0,2.0,-1.0,2.0,inf,-1.000000,1
2,00089L107,0.000283,0.000000,0.000000,0.000000,6.336145e-17,0.000000,0.000000,0.0,1.0,...,2003-06-30,0.0,1.0,0.0,1.0,0.0,0.0,0.000000,NaN,0
3,001084102,0.000565,0.002545,0.120557,0.001189,1.308002e-03,468.522872,6.000000,0.0,6.0,...,2003-06-30,9.0,2.0,7.0,2.0,-2.0,0.0,0.000000,-0.222222,0
4,00108M102,0.000848,0.000283,0.124502,0.000048,2.362460e-03,480.410101,6.333333,0.0,3.0,...,2003-06-30,1.0,3.0,1.0,2.0,0.0,-1.0,-0.333333,0.000000,-1

In [39]:
net_degree_3['year_0'].unique()

array(['2003-06-30', '2004-06-30', '2005-06-30', '2006-06-30',
       '2007-06-30', '2008-06-30', '2009-06-30', '2010-06-30',
       '2011-06-30', '2012-06-30', '2013-06-30', '2014-06-30',
       '2015-06-30'], dtype=object)

In [40]:
factset_foundamental = pd.read_pickle('factset_foundamental.pkl')

In [45]:
factset_foundamental['year_0'].unique()

array(['2003-06-30', '2004-06-30', '2005-06-30', '2006-06-30',
       '2007-06-30', '2008-06-30', '2009-06-30', '2010-06-30',
       '2011-06-30', '2012-06-30', '2013-06-30', '2014-06-30',
       '2015-06-30', '2016-06-30'], dtype=object)

In [41]:
factset_foundamental.head()

,FS_PERM_SEC_ID,DATE,INDUSTRY_CODE,SECTOR_CODE,FF_GEN_IND,FF_ASSETS,FF_ASSETS_CURR_OTH,FF_ASSETS_OTH,FF_ASSET_TURN,FF_BPS_TANG,...,FF_SALES_PS,FF_SGA,FF_SGA_OTH_EXP,FF_STK_CHG_CF,FF_TCAP,FF_TURN_RATE,FF_UNUSUAL_EXP,FF_EBIT_OPER_ROA,cusip_9,year_0
15,B00M5L-S-SE,2002-12-31,1315,1300,1.0,84.6330,0.0000,3.7760,0.295582,-15.642801,...,10.561717,42.590000,42.590000,0.000,64.1830,NaN,0.000000,-40.362577,W59397104,2003-06-30
31,B00N7M-S-CH,2002-12-31,1235,1200,1.0,41420.1612,5720.2299,770.1639,0.598438,-1.871335,...,20.287744,6274.238143,6274.238143,0.000,12395.9055,NaN,566.283829,1.478513,H0010V101,2003-06-30
47,B00QCP-S-BE,2002-12-31,3525,3500,1.0,187.3910,0.0000,7.5640,1.587023,13.781538,...,105.626238,NaN,5.370000,0.000,145.6670,NaN,0.059000,-0.039221,B1306K102,2003-06-30
52,B00RFQ-S-FR,2002-12-31,1210,1200,1.0,82.8320,0.1100,0.1350,1.274577,5.754530,...,12.828194,NaN,1.459000,0.000,56.0170,NaN,0.017000,12.043458,F91651194,2003-06-30
68,B00SHR-S-GB,2002-12-31,4830,4800,6.0,1535.9110,NaN,16.7050,0.360527,0.760944,...,1.404050,150.457000,243.797000,83.706,1153.9770,NaN,0.000000,6.772340,G19684102,2003-06-30

In [42]:
funda_net_degree_3 = pd.merge(net_degree_3,factset_foundamental, how = 'inner', on = ['cusip_9', 'year_0'] )

In [43]:
funda_net_degree_3.to_pickle('funda_net_degree_3.pkl')

In [44]:
funda_net_degree_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 66328 entries, 0 to 66327
Data columns (total 92 columns):
cusip_9                    66328 non-null object
out_degree_centrality      66328 non-null float64
in_degree_centrality       66328 non-null float64
closeness_centrality       66328 non-null float64
betweenness_centrality     66328 non-null float64
eigenvector_centrality     66328 non-null float64
harmonic_centrality        66328 non-null float64
average_neighbor_degree    66328 non-null float64
square_clustering          66328 non-null float64
core_number                66328 non-null float64
pagerank                   66328 non-null float64
hubs                       66328 non-null float64
authorities                66328 non-null float64
year_0                     66328 non-null object
in_degree_0                66328 non-null float64
out_degree_0               66328 non-null float64
in_degree_1                66328 non-null float64
out_degree_1               66328 non-null float64
in_diff                    66328 non-null float64
out_diff                   66328 non-null float64
out_diff_ratio             49994 non-null float64
in_diff_ratio              53472 non-null float64
out_group                  66328 non-null int64
FS_PERM_SEC_ID             66328 non-null object
DATE                       66328 non-null datetime64[ns]
INDUSTRY_CODE              66328 non-null object
SECTOR_CODE                66328 non-null object
FF_GEN_IND                 66325 non-null float64
FF_ASSETS                  66221 non-null float64
FF_ASSETS_CURR_OTH         57697 non-null float64
FF_ASSETS_OTH              66189 non-null float64
FF_ASSET_TURN              65539 non-null float64
FF_BPS_TANG                65952 non-null float64
FF_CAPEX                   65991 non-null float64
FF_CAPEX_SALES             64983 non-null float64
FF_COGS                    59979 non-null float64
FF_COM_EQ_ASSETS           66211 non-null float64
FF_CURR_RATIO              57707 non-null float64
FF_DEBT_ASSETS             66186 non-null float64
FF_DEBT_CF                 65376 non-null float64
FF_DEBT_EBITDA_OPER        52072 non-null float64
FF_EBITDA_OPER             61409 non-null float64
FF_EBIT_OPER               61676 non-null float64
FF_ENTRPR_VAL              63279 non-null float64
FF_EPS_DIL                 63652 non-null float64
FF_EPS_DIL_BEF_UNUSUAL     63534 non-null float64
FF_FIN_ACTIV_OTH_CF        65127 non-null float64
FF_FIN_CF                  66084 non-null float64
FF_FREE_CF                 65903 non-null float64
FF_GROSS_MGN               59064 non-null float64
FF_INT_EXP_NET             64311 non-null float64
FF_INT_INC_AFT_PROV        3009 non-null float64
FF_INT_INC_NET             5199 non-null float64
FF_INT_MGN                 1606 non-null float64
FF_INVEST_ADV              62504 non-null float64
FF_INVEST_CF               66085 non-null float64
FF_INVEST_PURCH_SALE_CF    65114 non-null float64
FF_INVEST_USES_CF          62688 non-null float64
FF_LIABS                   66217 non-null float64
FF_LIABS_CURR_OTH          58449 non-null float64
FF_LIABS_OTH               66221 non-null float64
FF_LOSS_CLAIM_RSRV         1753 non-null float64
FF_MISC_FUNDS_CF           66058 non-null float64
FF_MKT_VAL                 63283 non-null float64
FF_NET_DEBT                66161 non-null float64
FF_NET_INC                 66312 non-null float64
FF_NET_INC_AFT_XORD        66316 non-null float64
FF_NET_INC_BASIC           66307 non-null float64
FF_NET_MGN                 65255 non-null float64
FF_NON_OPER_INC            66298 non-null float64
FF_OPER_CF                 66060 non-null float64
FF_OPER_INC_AFT_INT        1650 non-null float64
FF_OPER_INC_BEF_INT        1780 non-null float64
FF_OPER_MGN                65044 non-null float64
FF_PAY_OUT_RATIO           47548 non-null float64
FF_PBK                     61085 non-null float64
FF_PCF                     51366 non-null float64
FF_PE                      47439 non-null float64
FF_PSALES                  62199 non-null float64
FF_PTX_MGN                 65249 non-null float64
FF_QUICK_RATIO             56103 non-null float64
FF_ROA                     65555 non-null float64
FF_ROE                     63382 non-null float64
FF_ROTC                    64989 non-null float64
FF_SALES_PS                65819 non-null float64
FF_SGA                     60173 non-null float64
FF_SGA_OTH_EXP             66202 non-null float64
FF_STK_CHG_CF              65460 non-null float64
FF_TCAP                    66190 non-null float64
FF_TURN_RATE               30275 non-null float64
FF_UNUSUAL_EXP             63011 non-null float64
FF_EBIT_OPER_ROA           30671 non-null float64
dtypes: datetime64[ns](1), float64(85), int64(1), object(5)
memory usage: 47.1+ MB

In [25]:
funda_net_degree_3.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,FF_ROE,FF_ROTC,FF_SALES_PS,FF_SGA,FF_SGA_OTH_EXP,FF_STK_CHG_CF,FF_TCAP,FF_TURN_RATE,FF_UNUSUAL_EXP,FF_EBIT_OPER_ROA
0,000360206,0.000813,0.000000,0.000000,0.000000,6.589818e-18,0.000000,1.666667,0.0,3.0,...,10.852892,10.429176,2.648424,15.214,15.214,-4.501,71.446,45.429980,0.000,NaN
1,000361105,0.000542,0.000000,0.000000,0.000000,6.589818e-18,0.000000,3.500000,0.0,2.0,...,1.174515,0.633839,20.127130,82.765,82.765,0.000,553.742,142.297980,3.504,NaN
2,000957100,0.000542,0.000000,0.000000,0.000000,6.589818e-18,0.000000,10.000000,0.0,1.0,...,6.877252,6.877252,48.262684,176.667,176.667,-1.039,442.161,67.102984,0.000,NaN
3,001031103,0.000271,0.000000,0.000000,0.000000,6.589818e-18,0.000000,1.000000,0.0,1.0,...,-0.826840,-0.132171,97.366952,106.715,106.715,0.522,316.327,35.521170,-0.512,NaN
4,001084102,0.000542,0.001896,0.115546,0.000721,1.337726e-03,472.720102,6.000000,0.0,5.0,...,13.639682,7.565147,55.160042,613.500,613.500,303.000,2581.000,280.466111,0.100,NaN