In [1]:
# data clean packages
import pandas as pd
import numpy as np
import datetime as dt

# plot packages
import seaborn as sns; sns.set(color_codes=True)
import matplotlib.pyplot as plt

# network features

In [3]:
df_net_deg = pd.read_pickle('df_net_deg.pkl')

In [4]:
df_net_deg.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,hubs,authorities,year,in_degree_2015,out_degree_2015,cusip_8,in_degree_2016,out_degree_2016,out_diff,group
4,931142103,0.001738,0.024028,0.183122,1.207448e-02,1.554571e-01,3534.923810,8.137931,0.002457,19,...,0.000064,0.004436,2015-12-31,401,29,93114210,432,27,-2,-1
9,171779309,0.000899,0.001438,0.117249,1.218009e-04,4.007248e-03,2102.871934,21.000000,0.001077,17,...,0.000171,0.000343,2015-12-31,24,15,17177930,22,12,-3,-1
10,J13650106,0.000120,0.000060,0.000060,2.437062e-07,2.312490e-23,1.000000,95.500000,0.000000,3,...,0.000047,0.000008,2015-12-31,1,2,J1365010,2,1,-1,-1
14,292475209,0.001498,0.000719,0.127585,3.270477e-04,7.370309e-03,2305.819048,58.400000,0.003439,19,...,0.000421,0.000230,2015-12-31,12,25,29247520,10,22,-3,-1
18,548661107,0.000240,0.006531,0.158773,1.407380e-03,3.743791e-02,2965.220238,29.750000,0.001914,18,...,0.000053,0.001283,2015-12-31,109,4,54866110,121,2,-2,-1

# compustat

In [59]:
comp_2014 = pd.read_pickle('comp_2014.pkl')

In [60]:
comp_2014 = comp_2014.rename(columns = {'cusip': 'cusip_9'})

In [61]:
comp_2014.to_pickle('comp_2014.pkl')

In [62]:
comp_2014.head()

,index,gvkey,datadate,cusip_9,fyear,adrr,ajex,ajp,currtr,curuscn,...,adjex_c,cshtr_f,dvpsp_f,dvpsx_f,mkvalt,prcc_f,prch_f,prcl_f,adjex_f,rank
0,153,001004,2015-05-31,000361105,2014.0,NaN,NaN,NaN,NaN,NaN,...,1.0,6.540965e+07,0.3000,0.3000,1046.3954,29.54,34.24,22.37,1.0,NaN
1,403,001119,2014-12-31,006212104,2014.0,NaN,1.0,1.0,1.0,NaN,...,1.0,3.411404e+07,1.1800,1.1800,NaN,13.68,14.90,12.14,1.0,NaN
2,1294,001045,2014-12-31,02376R102,2014.0,NaN,NaN,NaN,NaN,NaN,...,1.0,3.119956e+09,0.2000,0.2000,37405.5843,53.63,54.64,25.06,1.0,NaN
3,1460,001050,2014-12-31,125141101,2014.0,NaN,NaN,NaN,NaN,NaN,...,1.0,2.068057e+07,0.2300,0.2300,408.1892,15.54,18.90,12.40,1.0,NaN
4,1594,001417,2014-06-30,46132L107,2014.0,NaN,1.0,1.0,1.0,NaN,...,1.0,9.303613e+06,1.1757,1.1757,NaN,19.18,19.19,17.15,1.0,NaN

In [63]:
revere_comp_2014 = pd.merge(df_net_deg, comp_2014, how = 'inner', on = 'cusip_9')

In [64]:
revere_comp_2014.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3480 entries, 0 to 3479
Columns: 939 entries, cusip_9 to rank
dtypes: float64(926), int64(8), object(5)
memory usage: 25.0+ MB

In [65]:
revere_comp_2014.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,adjex_c,cshtr_f,dvpsp_f,dvpsx_f,mkvalt,prcc_f,prch_f,prcl_f,adjex_f,rank
0,931142103,0.001738,0.024028,0.183122,0.012074,0.155457,3534.923810,8.137931,0.002457,19,...,1.0,1.650449e+09,1.92,1.92,274315.4400,84.98,90.97,72.2700,1.0,NaN
1,171779309,0.000899,0.001438,0.117249,0.000122,0.004007,2102.871934,21.000000,0.001077,17,...,1.0,9.138388e+08,0.00,0.00,1792.9848,16.76,27.16,13.7699,1.0,NaN
2,292475209,0.001498,0.000719,0.127585,0.000327,0.007370,2305.819048,58.400000,0.003439,19,...,1.0,2.959748e+08,0.00,0.00,404.3124,5.70,8.99,4.5100,1.0,NaN
3,548661107,0.000240,0.006531,0.158773,0.001407,0.037438,2965.220238,29.750000,0.001914,18,...,1.0,1.400280e+09,0.82,0.87,65049.6000,67.76,71.11,44.1300,1.0,NaN
4,501044101,0.000180,0.005333,0.148569,0.000648,0.023799,2715.382937,27.333333,0.000000,16,...,2.0,8.703359e+08,0.68,0.68,33627.3500,69.05,70.06,35.1300,2.0,NaN

In [44]:
revere_comp_2014.to_pickle('revere_comp_2014.pkl')

In [56]:
len(revere_comp_2014)

3480

In [46]:
revere_comp_2014 = pd.read_pickle('revere_comp_2014.pkl')

In [68]:
revere_comp_2014 = revere_comp_2014.dropna(thresh = 1000, axis =1)

In [69]:
revere_comp_2014.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3480 entries, 0 to 3479
Data columns (total 74 columns):
cusip_9                    3480 non-null object
out_degree_centrality      3480 non-null float64
in_degree_centrality       3480 non-null float64
closeness_centrality       3480 non-null float64
betweenness_centrality     3480 non-null float64
eigenvector_centrality     3480 non-null float64
harmonic_centrality        3480 non-null float64
average_neighbor_degree    3480 non-null float64
square_clustering          3480 non-null float64
core_number                3480 non-null int64
pagerank                   3480 non-null float64
hubs                       3480 non-null float64
authorities                3480 non-null float64
year                       3480 non-null object
in_degree_2015             3480 non-null int64
out_degree_2015            3480 non-null int64
cusip_8                    3480 non-null object
in_degree_2016             3480 non-null int64
out_degree_2016            3480 non-null int64
out_diff                   3480 non-null int64
group                      3480 non-null int64
index                      3480 non-null int64
gvkey                      3480 non-null object
datadate                   3480 non-null object
fyear                      3480 non-null float64
fyr                        3480 non-null float64
pddur                      3480 non-null float64
src                        3478 non-null float64
upd                        3480 non-null float64
at                         3365 non-null float64
capx                       3164 non-null float64
cogs                       3261 non-null float64
cshfd                      3383 non-null float64
cshpri                     3399 non-null float64
dltt                       3007 non-null float64
dp                         3159 non-null float64
epsfi                      3346 non-null float64
epsfx                      3346 non-null float64
epspi                      3336 non-null float64
epspx                      3347 non-null float64
ib                         3408 non-null float64
ibmii                      3330 non-null float64
mii                        3244 non-null float64
ni                         3385 non-null float64
nopi                       3266 non-null float64
pi                         3358 non-null float64
ppent                      3100 non-null float64
reuna                      3204 non-null float64
sale                       3411 non-null float64
seq                        3414 non-null float64
teq                        3327 non-null float64
txt                        3361 non-null float64
wcap                       2560 non-null float64
xido                       3398 non-null float64
xint                       2939 non-null float64
xsga                       2702 non-null float64
exchg                      3480 non-null float64
naicsh                     3246 non-null float64
sich                       3176 non-null float64
cshtr_c                    3434 non-null float64
dvpsp_c                    3458 non-null float64
dvpsx_c                    3458 non-null float64
prcc_c                     3436 non-null float64
prch_c                     3436 non-null float64
prcl_c                     3436 non-null float64
adjex_c                    3458 non-null float64
cshtr_f                    3434 non-null float64
dvpsp_f                    3458 non-null float64
dvpsx_f                    3458 non-null float64
mkvalt                     3235 non-null float64
prcc_f                     3436 non-null float64
prch_f                     3436 non-null float64
prcl_f                     3436 non-null float64
adjex_f                    3459 non-null float64
dtypes: float64(61), int64(8), object(5)
memory usage: 2.0+ MB

In [25]:
revere_comp_2014['out_diff_ratio'] = revere_comp_2014['out_diff']/revere_comp_2014['out_degree_2015']

In [27]:
revere_comp_2014['out_diff_ratio'] = revere_comp_2014['out_diff_ratio'].replace([np.inf, -np.inf], 0)

In [28]:
revere_comp_2014 = revere_comp_2014.fillna(0)

In [29]:
revere_comp_2014.to_pickle('revere_comp_2014.pkl')

# institute

In [31]:
institute = pd.read_pickle('s34type4_2015.pkl')

In [32]:
institute.head()

        fdate     cusip    mgrno  type     change   cusip_8
0  2015-03-31  39874310   8842.0   5.0   -26800.0  39874310
1  2015-03-31  60871120   9010.0   4.0 -1301654.0  60871120
2  2015-03-31  43164310  10204.0   5.0    -1450.0  43164310
3  2015-03-31  22989410  10346.0   5.0  -211139.0  22989410
4  2015-03-31  11143410  10387.0   5.0  -230202.0  11143410

In [33]:
revere_comp_inst = pd.merge(revere_comp_2014, institute, how = 'inner', on = 'cusip_8')

In [35]:
revere_comp_inst.to_pickle('revere_comp_inst.pkl')