In [17]:
import pandas as pd
import datetime as dt
import numpy as np

In [18]:
funda_net_degree_3 = pd.read_pickle('funda_net_degree_3.pkl')

In [19]:
funda_net_degree_3.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,FF_ROE,FF_ROTC,FF_SALES_PS,FF_SGA,FF_SGA_OTH_EXP,FF_STK_CHG_CF,FF_TCAP,FF_TURN_RATE,FF_UNUSUAL_EXP,FF_EBIT_OPER_ROA
0,000360206,0.000848,0.000000,0.000000,0.000000,6.336145e-17,0.000000,2.000000,0.0,3.0,...,26.009559,24.715813,2.229411,15.071,15.071,-3.116,65.876,66.335480,0.0,NaN
1,000361105,0.000000,0.000283,0.138689,0.000000,6.321229e-03,548.415620,0.000000,0.0,1.0,...,-18.122614,-10.674358,22.584011,85.037,85.037,34.129,570.459,163.973920,86.0,NaN
2,001084102,0.000565,0.002545,0.120557,0.001189,1.308002e-03,468.522872,6.000000,0.0,6.0,...,-7.949901,-4.351277,39.389488,282.400,282.400,10.300,1354.500,229.720701,86.8,NaN
3,00108M102,0.000848,0.000283,0.124502,0.000048,2.362460e-03,480.410101,6.333333,0.0,3.0,...,9.880220,4.344855,6.024062,8.283,8.283,0.181,17.792,30.613838,0.0,NaN
4,001204106,0.000283,0.001414,0.115748,0.000250,5.949723e-04,446.904182,2.000000,0.0,4.0,...,12.863744,4.895903,15.351590,NaN,303.400,19.700,2122.900,67.773838,0.0,NaN

In [20]:
len(funda_net_degree_3['INDUSTRY_CODE'].unique())

129

In [21]:
funda_net_degree_3['FF_GEN_IND'].unique()

array([ 1.,  2.,  3.,  4.,  6.,  5., nan])

In [22]:
sector_dummy = pd.get_dummies(funda_net_degree_3['SECTOR_CODE'])

In [23]:
new_columns = []
for x in sector_dummy.columns:
    a = 'SECTOR_CODE' + str(x)
    new_columns.append(a)

In [24]:
new_columns

['SECTOR_CODE1100',
 'SECTOR_CODE1200',
 'SECTOR_CODE1300',
 'SECTOR_CODE1400',
 'SECTOR_CODE2100',
 'SECTOR_CODE2200',
 'SECTOR_CODE2300',
 'SECTOR_CODE2400',
 'SECTOR_CODE3100',
 'SECTOR_CODE3200',
 'SECTOR_CODE3250',
 'SECTOR_CODE3300',
 'SECTOR_CODE3350',
 'SECTOR_CODE3400',
 'SECTOR_CODE3500',
 'SECTOR_CODE4600',
 'SECTOR_CODE4700',
 'SECTOR_CODE4800',
 'SECTOR_CODE4900',
 'SECTOR_CODE6000']

In [25]:
#sector_dummy.rename

In [26]:
indexlist = sector_dummy.index
X = np.array(sector_dummy.loc[:,:])
sector_dummy1 = pd.DataFrame(X, columns =new_columns,index=indexlist)

In [27]:
sector_dummy1.head()

,SECTOR_CODE1100,SECTOR_CODE1200,SECTOR_CODE1300,SECTOR_CODE1400,SECTOR_CODE2100,SECTOR_CODE2200,SECTOR_CODE2300,SECTOR_CODE2400,SECTOR_CODE3100,SECTOR_CODE3200,SECTOR_CODE3250,SECTOR_CODE3300,SECTOR_CODE3350,SECTOR_CODE3400,SECTOR_CODE3500,SECTOR_CODE4600,SECTOR_CODE4700,SECTOR_CODE4800,SECTOR_CODE4900,SECTOR_CODE6000
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [28]:
sector_funda_net_degree_3 = pd.concat([funda_net_degree_3,sector_dummy1], axis = 1)

In [29]:
sector_funda_net_degree_3.to_pickle('sector_funda_net_degree_3.pkl')

In [30]:
sector_funda_net_degree_3.head()

,cusip_9,out_degree_centrality,in_degree_centrality,closeness_centrality,betweenness_centrality,eigenvector_centrality,harmonic_centrality,average_neighbor_degree,square_clustering,core_number,...,SECTOR_CODE3250,SECTOR_CODE3300,SECTOR_CODE3350,SECTOR_CODE3400,SECTOR_CODE3500,SECTOR_CODE4600,SECTOR_CODE4700,SECTOR_CODE4800,SECTOR_CODE4900,SECTOR_CODE6000
0,000360206,0.000848,0.000000,0.000000,0.000000,6.336145e-17,0.000000,2.000000,0.0,3.0,...,0,0,0,0,0,0,0,0,0,0
1,000361105,0.000000,0.000283,0.138689,0.000000,6.321229e-03,548.415620,0.000000,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2,001084102,0.000565,0.002545,0.120557,0.001189,1.308002e-03,468.522872,6.000000,0.0,6.0,...,0,0,0,0,0,0,0,0,0,0
3,00108M102,0.000848,0.000283,0.124502,0.000048,2.362460e-03,480.410101,6.333333,0.0,3.0,...,0,0,0,0,0,0,0,0,0,0
4,001204106,0.000283,0.001414,0.115748,0.000250,5.949723e-04,446.904182,2.000000,0.0,4.0,...,0,0,0,0,0,0,1,0,0,0